version: '3.7'

networks: 
  host:
    name: host
    ipam:
      config: 
        - subnet: 172.20.0.0/24
    driver: bridge

services:
  nginx:
    environment:
      - TZ=America/Sao_Paulo
    container_name: nginx
    hostname: nginx
    networks: 
      - host
    ports:
      - "80:80"
      - "443:443"
    privileged: true
    restart: unless-stopped
    image: 'nginx:latest'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

  docs:
    environment:
      - TZ=America/Sao_Paulo
    container_name: docs
    hostname: docs
    networks: 
      - host
    privileged: true
    restart: unless-stopped
    image: '<user>/docs:${TAG}'